from __future__ import annotations

import argparse
import json
import math
import re
from collections import Counter
from pathlib import Path
from statistics import mean, pstdev


STOCK_PATTERNS: dict[str, re.Pattern[str]] = {
    "importance-framing": re.compile(r"\b(?:it is important to|it should be noted that|it is worth noting)\b", re.I),
    "generic-emphasis": re.compile(r"\b(?:this (?:highlights|underscores|showcases)|a key (?:finding|insight|advantage))\b", re.I),
    "stock-transition": re.compile(r"\b(?:moreover|furthermore|in conclusion|overall,)\b", re.I),
    "inflated-claim": re.compile(r"\b(?:groundbreaking|revolutionary|transformative|paves? the way|paradigm shift)\b", re.I),
    "formulaic-contrast": re.compile(r"\bnot only\b.{0,100}\bbut also\b", re.I | re.S),
    "reader-address": re.compile(r"\b(?:let us|we can see that|as you can see)\b", re.I),
}


def prose_only(text: str) -> str:
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", text)
    text = re.sub(r"^\|.*$", "", text, flags=re.M)
    text = re.sub(r"^[-:| ]+$", "", text, flags=re.M)
    text = re.sub(r"\\\[.*?\\\]", "", text, flags=re.S)
    text = re.sub(r"\[@[^\]]+\]", "", text)
    text = re.sub(r"^#{1,6}\s+.*$", "", text, flags=re.M)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def sentence_list(text: str) -> list[str]:
    return [part.strip() for part in re.split(r"(?<=[.!?])\s+", text) if len(part.split()) >= 4]


def paragraph_list(text: str) -> list[str]:
    return [part.strip() for part in re.split(r"\n\s*\n", text) if len(part.split()) >= 15]


def heuristic_audit(text: str) -> dict[str, object]:
    prose = prose_only(text)
    sentences = sentence_list(prose)
    paragraphs = paragraph_list(prose)
    phrase_hits: list[dict[str, object]] = []
    for label, pattern in STOCK_PATTERNS.items():
        for match in pattern.finditer(prose):
            phrase_hits.append({"category": label, "text": match.group(0), "offset": match.start()})

    openings = Counter()
    for sentence in sentences:
        words = re.findall(r"[A-Za-z]+", sentence.lower())
        if len(words) >= 2:
            openings[" ".join(words[:2])] += 1
    repeated_openings = {key: value for key, value in openings.items() if value >= 4}

    paragraph_lengths = [len(paragraph.split()) for paragraph in paragraphs]
    paragraph_cv = 0.0
    if paragraph_lengths and mean(paragraph_lengths):
        paragraph_cv = pstdev(paragraph_lengths) / mean(paragraph_lengths)

    # This is a style-risk index, not an authorship probability. It is intentionally
    # conservative for technical prose and is only used to locate passages for review.
    repeated_excess = sum(max(0, value - 3) for value in repeated_openings.values())
    uniformity_penalty = max(0.0, 0.35 - paragraph_cv) * 20.0
    risk = min(100.0, len(phrase_hits) * 5.0 + repeated_excess * 1.5 + uniformity_penalty)
    return {
        "scope": {
            "words": len(prose.split()),
            "sentences": len(sentences),
            "paragraphs": len(paragraphs),
        },
        "stock_phrase_hits": phrase_hits,
        "repeated_sentence_openings": repeated_openings,
        "paragraph_length_cv": paragraph_cv,
        "style_risk_index_0_to_100": risk,
        "interpretation": "Editing diagnostic only; not a probability that the text was generated by AI.",
    }


def chunk_for_model(tokenizer, text: str, max_tokens: int = 430) -> list[str]:
    paragraphs = paragraph_list(prose_only(text))
    chunks: list[str] = []
    current: list[str] = []
    current_tokens = 0
    for paragraph in paragraphs:
        token_count = len(tokenizer.encode(paragraph, add_special_tokens=False))
        if current and current_tokens + token_count > max_tokens:
            chunks.append("\n\n".join(current))
            current, current_tokens = [], 0
        if token_count > max_tokens:
            words = paragraph.split()
            slice_words: list[str] = []
            for word in words:
                candidate = " ".join(slice_words + [word])
                if slice_words and len(tokenizer.encode(candidate, add_special_tokens=False)) > max_tokens:
                    chunks.append(" ".join(slice_words))
                    slice_words = [word]
                else:
                    slice_words.append(word)
            if slice_words:
                chunks.append(" ".join(slice_words))
            continue
        current.append(paragraph)
        current_tokens += token_count
    if current:
        chunks.append("\n\n".join(current))
    return chunks


def legacy_detector_audit(text: str, model_name: str) -> dict[str, object]:
    import torch
    from transformers import AutoModelForSequenceClassification, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    id2label = {int(key): str(value) for key, value in model.config.id2label.items()}
    generated_ids = [index for index, label in id2label.items() if re.search(r"fake|generated|machine", label, re.I)]
    if not generated_ids:
        raise RuntimeError(f"Cannot identify generated-text label from {id2label!r}")

    chunks = chunk_for_model(tokenizer, text)
    records = []
    weighted_sum = 0.0
    total_tokens = 0
    with torch.inference_mode():
        for index, chunk in enumerate(chunks):
            encoded = tokenizer(chunk, return_tensors="pt", truncation=True, max_length=512).to(device)
            probabilities = torch.softmax(model(**encoded).logits, dim=-1)[0].cpu()
            generated_probability = float(probabilities[generated_ids].sum().item())
            tokens = int(encoded["input_ids"].shape[1])
            total_tokens += tokens
            weighted_sum += generated_probability * tokens
            records.append(
                {
                    "chunk": index + 1,
                    "tokens": tokens,
                    "generated_probability": generated_probability,
                    "opening": chunk[:160].replace("\n", " "),
                }
            )

    return {
        "model": model_name,
        "model_revision": getattr(model.config, "_commit_hash", None),
        "labels": id2label,
        "chunks": records,
        "token_weighted_generated_probability": weighted_sum / max(1, total_tokens),
        "limitation": (
            "Legacy out-of-domain detector diagnostic. It was not trained to identify current models or "
            "technical manuscripts, so its score is not evidence of authorship and must not be optimized against."
        ),
    }


def markdown_report(payload: dict[str, object]) -> str:
    heuristic = payload["heuristic"]
    lines = [
        "# Local AI-style audit",
        "",
        "This report is an editing aid, not an authorship test. Automated AI-text detectors have substantial domain and model shift, especially for formulaic academic prose. The manuscript retains a transparent generative-AI disclosure regardless of these diagnostics.",
        "",
        "## Rule-based style review",
        "",
        f"- Words reviewed: {heuristic['scope']['words']}",
        f"- Stock-phrase hits: {len(heuristic['stock_phrase_hits'])}",
        f"- Paragraph-length coefficient of variation: {heuristic['paragraph_length_cv']:.3f}",
        f"- AI-style risk index: {heuristic['style_risk_index_0_to_100']:.1f}/100 (not an AI probability)",
        "",
    ]
    if heuristic["stock_phrase_hits"]:
        lines.extend(["Flagged phrases:", ""])
        for hit in heuristic["stock_phrase_hits"]:
            lines.append(f"- {hit['category']}: `{hit['text']}`")
        lines.append("")
    else:
        lines.extend(["No stock phrases in the configured local rule set were detected.", ""])

    legacy = payload.get("legacy_detector")
    if legacy:
        lines.extend(
            [
                "## Legacy model diagnostic",
                "",
                f"- Model: `{legacy['model']}`",
                f"- Token-weighted generated-text score: {100.0 * legacy['token_weighted_generated_probability']:.1f}%",
                f"- Limitation: {legacy['limitation']}",
                "",
                "Chunk scores:",
                "",
                "| Chunk | Tokens | Generated-text score | Opening |",
                "| ---: | ---: | ---: | --- |",
            ]
        )
        for record in legacy["chunks"]:
            opening = str(record["opening"]).replace("|", "\\|")
            lines.append(
                f"| {record['chunk']} | {record['tokens']} | {100.0 * record['generated_probability']:.1f}% | {opening} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run local, non-evidentiary AI-style diagnostics.")
    parser.add_argument("--input", type=Path, default=Path("paper/MANUSCRIPT_DRAFT_v1.md"))
    parser.add_argument("--json", type=Path, default=Path("paper/AI_STYLE_AUDIT.json"))
    parser.add_argument("--markdown", type=Path, default=Path("paper/AI_STYLE_AUDIT.md"))
    parser.add_argument("--legacy-model", default=None)
    args = parser.parse_args()

    text = args.input.read_text(encoding="utf-8")
    payload: dict[str, object] = {
        "input": args.input.as_posix(),
        "heuristic": heuristic_audit(text),
    }
    if args.legacy_model:
        payload["legacy_detector"] = legacy_detector_audit(text, args.legacy_model)
    args.json.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.markdown.write_text(markdown_report(payload) + "\n", encoding="utf-8")
    print(json.dumps({"status": "ok", "heuristic": payload["heuristic"], "legacy": bool(args.legacy_model)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
